name: Create a PR automatically
on:
  push:
    branches: ['main']
    paths:
      - test/**

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Creating Pull Requests
        run: |
          gh pr create -B main -H ${{ steps.branch_name.outputs.branch_name }} --title "Merge ${{ steps.branch_name.outputs.branch_name }} into main" --body "Created by GitHub Action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
