name: Create a PR automatically
on:
  push:
    branches: ["*"]
    paths:
      - test/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Title and Body
        run: |
          # Generate a random title
          title="Merge feat into main - $(date +%Y-%m-%d)"

          # Generate a random body
          body="Created by GitHub Action on $(date). This is a dynamically generated body for the pull request."

          export PR_TITLE="$title"
          export PR_BODY="$body"

      - name: Creating Pull Requests
        run: |
          gh pr create -B main -H ${{ steps.vars.outputs.short_ref }} --title "Merge ${PR_TITLE} into main" --body "Created by GitHub Action at ${PR_BODY}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
