name: Create a PR automatically
on:
  push:
    branches: ["*"]
    paths:
      - test/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Title and Body
        run: |
          echo "PR_TITLE=Merge ${{ steps.vars.outputs.short_ref }} into main - $(date)" >> $GITHUB_ENV

          echo "PR_BODY=Created by GitHub Action on $(date). This is a dynamically generated body for the pull request." >> $GITHUB_ENV

      - name: Creating Pull Requests
        run: |
          gh pr create -B main -H ${{ steps.vars.outputs.short_ref }} --title "${{env.PR_TITLE}}" --body "${{env.PR_BODY}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
